browser=Chrome
URL=https://www.kapruka.com/
# URL1 = "https://int.zigzag.lk/collections/work-wear-1"
# //Url to print custom cakes
# URL2 = https://www.kapruka.com/shops/cakes/customCakes/customCakesStep1.jsp








